version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  Verademo-dotnet:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
    working_directory: $CIRCLE_WORKING_DIRECTORY 
    steps:
      - checkout:
          path: working_directory
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "VeraDemoNet.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - \project\verademo-dotnet\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "VeraDemoNet.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\VeraDemoNet.dll
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\VeraDemoNet.dll