version: 2.1

orbs:
  win: circleci/windows@2.4.0

workflows:
  Verademo-dotnet:
    jobs:
      - build

jobs:
  build:
    executor:
      name: win/default
      version: edge
    working_directory: C:\Users\circleci\project\VeraDemoNet 
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "VeraDemoNet.csproj" }}
      - run:
          name: "Find the csproj file"
          command: pwd; dir 
      - run:
          name: "Install project dependencies was dotnet.exe restore"
          command: nuget.exe restore C:\Users\circleci\project\VeraDemoNet.sln -Verbosity Detailed
      - save_cache:
          paths:
            - C:\Users\circleci\project\
            - C:\Users\circleci\project\VeraDemoNet\
          key: dotnet-packages-v1-{{ checksum "VeraDemoNet.csproj" }}
      - run:
          name: "Run Build step"
          command: msbuild /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DebugSymbols=true
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\VeraDemoNet.dll
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\VeraDemoNet.dll