name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
         3.1.*
         5.0.*
    - name: Restore dependencies
      run: nuget restore VeraDemoNet.sln
    - name: Clean Default Build
      run: msbuild VeraDemoNet.sln /t:clean
    - name: Build - was dotnet build --no-restore
      run: msbuild VeraDemoNet\VeraDemoNet.csproj -t:rebuild -verbosity:diag -property:Debug=Release

    - name: Test
      run: dotnet test --no-build --verbosity normal 
    - name: List files in the repository
      run: |
          ls -al ${{ github.workspace }}
    - uses: actions/upload-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them.
      with:
          name: CodePackage
          path: '**/*.dll' # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact

    - uses: veracode/veracode-uploadandscan-action@master # Run the uploadandscan action. Inputs are described above.
      with:
          appname: '${{ secrets.VERACODE_APP_NAME }}'
          filepath: app/target/verademo.war
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          scantimeout: 60
          createprofile: false
