name: Veracode-SAST
'on':
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment'
        required: true
        default: 'production'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-2019
 
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      - name: Restore dependencies
        run: nuget restore VeraDemoNet.sln
      - name: Clean Default Build
        run: 'msbuild VeraDemoNet.sln /t:clean'
      - name: Build - was dotnet build --no-restore
        run: >-
          msbuild.exe VeraDemoNet.sln /p:DeployOnBuild=true
          /p:WebPublishMethod=Package /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true /p:PackageLocation=./..
          /p:DebugSymbols=true /t:build
      - name: List files in the repository and copy artifact
        run: |
          dir ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}\artifact
          copy VeraDemoNet.zip ${{ github.workspace }}\artifact
          dir ${{ github.workspace }}\artifact
      - name: Upload artifact for Security Steps
        uses: actions/upload-artifact@v4 # Copy files from repository to docker container so the next uploadandscan action can access them.
        with:
          name: VeraDemoNet.zip
          path: ${{ github.workspace }}\artifact\VeraDemoNet.zip
      
  security:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out main branch
      uses: actions/checkout@v4 
    - name: Download Artifact from Previous Job
      uses: actions/download-artifact@v4
      with:
        path: '${{ github.workspace }}/artifact'
    - name: Verify file in the repository
      run: |
          ls -la ${{ github.workspace }}/artifact/VeraDemoNet.zip || echo "File does not exist"
    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@master
      with:
          appname: '${{ secrets.VERACODE_APP_NAME }}'
          createprofile: false
          filepath: ${{ github.workspace }}/artifact/VeraDemoNet.zip
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          deleteincompletescan: 2
          debug: true
#          createsandbox: 'true'
#          sandboxname: 'SANDBOXNAME'
#          scantimeout: 0
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'
